### ISSUE TITLE
direct grouping or aligned grouping

### ISSUE THREAD

**Issue by yiyayi-0123** [Blueprintf/pointlstm_gesture_recognition_pytorch#13]
Does the code use direct grouping or aligned grouping?

**Comment by ycmin95** [comment]
@yiyayi-0123 
You can choose the grouping mode by changing the [offsets parameter](https://github.com/ycmin95/pointlstm-gesture-recognition-pytorch/blob/master/experiments/pointlstm.yaml#L49).

**Comment by yiyayi-0123** [comment]
Thank you for your answer.
