### ISSUE TITLE
关于MSRaction数据集的问题

### ISSUE THREAD

**Issue by weiyutao886** [Blueprintf/pointlstm_gesture_recognition_pytorch#14]
您好，我想用MSRaction数据集运行并测试一下结果，但是数据集的读取遇到了问题，请问您能提供下您的读取MSRaction数据集的代码么

**Comment by ycmin95** [comment]
@weiyutao886 
You can follow the nvidia dataset processing [code](https://github.com/ycmin95/pointlstm-gesture-recognition-pytorch/blob/master/dataset/nvidia_process.py) to sample point cloud sequence from human regions.

**Comment by weiyutao886** [comment]
thank you ,i will try it again

**Comment by weiyutao886** [comment]
您好，经过数据预处理把数据集制作成了train和test两部分，每个里面都是.npy文件。我是一个小白请问您能提供下msraction数据集dataloader的思路或者代码么，我的邮箱935628178@qq.com，感谢

**Comment by weiyutao886** [comment]
可以提供下您的MSRACTION读取的dataloader的代码和数据集么，想尝试基于您的代码来进行动作识别的研究，非常感谢。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ycmin95/pointlstm-gesture-recognition-pytorch"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年10月14日(星期四) 下午5:24
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ycmin95/pointlstm-gesture-recognition-pytorch] 关于MSRaction数据集的问题 (#14)





 
@weiyutao886
 You can follow the nvidia dataset processing code to sample point cloud sequence from human regions.
 
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
