### ISSUE TITLE
CUDA out of memory

### ISSUE THREAD

**Issue by haddaa** [Blueprintf/pointlstm_gesture_recognition_pytorch#15]
When I'm running :` python main.py --phase=train --work-dir=PATH_TO_SAVE_RESULTS --device=0`
 I got this error :

`RuntimeError: CUDA out of memory. Tried to allocate 20.00 MiB (GPU 0; 6.00 GiB total capacity; 4.40 GiB already allocated; 0 bytes free; 4.81 GiB reserved in total by PyTorch)`

**Comment by ycmin95** [comment]
@hamza-hadda 
You can adopt smaller batch size by changing the [config file](https://github.com/ycmin95/pointlstm-gesture-recognition-pytorch/blob/master/experiments/pointlstm.yaml#L9).
