### ISSUE TITLE
Calculate the Accuracy for each epoche

### ISSUE THREAD

**Issue by haddaa** [Blueprintf/pointlstm_gesture_recognition_pytorch#16]
I want to calculate the accuracy of model for each epoch
I tried this way: https://stackoverflow.com/questions/51503851/calculate-the-accuracy-every-epoch-in-pytorch and it doesn't work

**Comment by haddaa** [comment]
it's worked with [this](https://androidkt.com/calculate-total-loss-and-accuracy-at-every-epoch-and-plot-using-matplotlib-in-pytorch/) but I don't if the results are corrects 
![epoch2](https://user-images.githubusercontent.com/23709435/138628479-c0a0300e-599a-4c05-a0f2-6effa38edb68.PNG)
![epoch1](https://user-images.githubusercontent.com/23709435/138628486-f26f96cf-93a0-4c4d-9ea2-a4e954e68afc.PNG)

**Comment by ycmin95** [comment]
@hamza-hadda 
You can set the [evaluation interval](https://github.com/ycmin95/pointlstm-gesture-recognition-pytorch/blob/master/experiments/pointlstm.yaml#L16) as 1.

**Comment by haddaa** [comment]
nothing changed

**Comment by ycmin95** [comment]
Relevant code can be found [here](https://github.com/ycmin95/pointlstm-gesture-recognition-pytorch/blob/master/experiments/main.py#L161).

**Comment by haddaa** [comment]
as I see her prec5 mean the accuracy yes ? but what about prec1?

**Comment by ycmin95** [comment]
Top-1 and top-5 accuracies.
