### ISSUE TITLE
Question about the application on mobile phone data

### ISSUE THREAD

**Issue by haddaa** [Blueprintf/pointlstm_gesture_recognition_pytorch#17]
hey ,
I want to ask you if we can use this model with images taken by phone's camera

**Comment by ycmin95** [comment]
In fact, we have tried to apply this method on Chinese sign language teaching system, which is based on Huawei Mate20 Pro. Details can be found in [this article](http://www.vr-ih.com/vrih/resource/article/unzip/1623307428875/VIRH-2021-03-2/4-21-00018/VRIH-D-21-00018-chenxilin_Yanxiao+ZHANG_L.pdf).

From our experience, point cloud based gesture/sign language recognition is efficient but less robust to viewpoint changes.

**Comment by haddaa** [comment]
thank you for your help I will read your article

**Comment by haddaa** [comment]
what do you mean by viewpoint changes ?

**Comment by ycmin95** [comment]
Refer to this [arXiv paper](https://arxiv.org/pdf/2109.07253.pdf).
