### ISSUE TITLE
PATH_TO_WEIGHTS

### ISSUE THREAD

**Issue by Cari24** [Blueprintf/pointlstm_gesture_recognition_pytorch#25]
Hello，where is the file "weights=PATH_TO_WEIGHTS", I can not find it. Kind regard!

**Comment by ycmin95** [comment]
It is the path to the pretrained weight. You can download the provided weights or adopt the trained weight.

**Comment by Cari24** [comment]
Where can I download the weight file? I prefer to use training weights, but I'm not very clear about the composition of the "path_to_weights" file mentioned in your code. I hope you can say it in detail. Thank you very much! Kind regard!

**Comment by ycmin95** [comment]
The download instruction can be found in readme, you can download through google drive or baiduyun.

**Comment by Cari24** [comment]
Ok, I will try it now. Thanks again for your reply patiently.

**Comment by Cari24** [comment]
Hello, I have trained the model on SHREC'17, I have the epoch_model.pt file. I just don' know how to extract the weight form the file. 
![image](https://user-images.githubusercontent.com/57899513/182781691-c9744f97-c36d-49de-a699-60387f7f3c29.png)

**Comment by Cari24** [comment]
I built this folder and put the model parameter files in it, but it still doesn't seem to work.
![image](https://user-images.githubusercontent.com/57899513/182782272-e0326dba-cfaf-4233-8cb5-56dff304b226.png)

Kind regard!

**Comment by ycmin95** [comment]
You can replace PATH_TO_WEIGHTS to the path tho the epoch_model.pt
e.g. python main.py --phase=test --weights=./epoch200_model.pt

Relevant code can be found [here](https://github.com/ycmin95/pointlstm-gesture-recognition-pytorch/blob/master/experiments/main.py#L87)

**Comment by Cari24** [comment]
I have solve this problem by modify pointlstm.yaml file, thanks, my friend! I love you !

**Comment by Cari24** [comment]
Hi, I have solved this problem by modifying the file "pointlstm.yaml". Love you, my friend, Kind regard!

**Comment by zeng947** [comment]
> 

how?i encounter the same problem!Kind regard

**Comment by ycmin95** [comment]
@zeng947 
The 'load weights' option is used to load pretrained model for inference or debug, you can change the weight path by change the [config file](https://github.com/ycmin95/pointlstm-gesture-recognition-pytorch/blob/master/experiments/pointlstm.yaml#L18) or through the comand. PATH_TO_WEIGHTS means the path to the pretrained weights, rather than the string "PATH_TO_WEIGHTS".

**Comment by zeng947** [comment]
> @zeng947 The 'load weights' option is used to load pretrained model for inference or debug, you can change the weight path by change the [config file](https://github.com/ycmin95/pointlstm-gesture-recognition-pytorch/blob/master/experiments/pointlstm.yaml#L18) or through the comand. PATH_TO_WEIGHTS means the path to the pretrained weights, rather than the string "PATH_TO_WEIGHTS".

thanks!i have solved it!
