### ISSUE TITLE
May I ask difference between SHREC data and NVGesture data pre-processing?

### ISSUE THREAD

**Issue by doyeon16** [Blueprintf/pointlstm_gesture_recognition_pytorch#6]
Hi, @Blueprintf 

Thank you for sharing your code.

I have a question about the code.

Unlike pre-processing code of SHREC data, NVGesture subtracts the value (= pts[:, 2])  from 255 when it preprocesses the data (in uvd2xyz_nvidia funtion in utils.py ). May I ask why?
Is there the difference between when you did it and when you didn't?

Thanks for reading

**Comment by Blueprintf** [comment]
If you visualize the NVGesture data, you will find that the closer pixels have larger depth values, which is different from the usual setting. We subtract the depth value (= pts[:, 2]) from 255 to do pose estimation in the initial attempts and keep this setting. Hope this can help you~

**Comment by ycmin95** [comment]
@doyeon16 If you visualize the NVGesture data, you will find that the closer pixels have larger depth values, which is different from the usual setting. We subtract the depth value (= pts[:, 2]) from 255 to do pose estimation in the initial attempts and keep this setting. Hope this can help you~

**Comment by doyeon16** [comment]
@Blueprintf 
Oh I see. 
Thanks for the quick reply.
